<?php

namespace App\Repositories;

use App\Models\OtherTeam;

class OtherTeamRepository extends Repository
{
    /**
     * @param $model
     */
    public function __construct(OtherTeam $otherTeam)
    {
        parent::__construct($otherTeam);
    }

    /**
     * @param $orderBy
     * @return mixed
     */
    public function all($orderBy = ['created_at' => 'desc'])
    {
        return parent::all($orderBy); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return mixed
     */
    public function find($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @return mixed
     */
    public function create(array $data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @param array $data
     * @return mixed
     */
    public function update($id, array $data)
    {
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return mixed
     */
    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
    public function getOtherTeamById($id){
        return parent::find($id);
    }

}
